# Generated by Django 6.1 on 2026-08-12 14:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('companies', '0001_initial'),
        ('workorders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('urgency', models.CharField(choices=[('low', 'Faible'), ('normal', 'Normale'), ('high', 'Haute'), ('critical', 'Critique')], default='normal', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='requests/photos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='requests/videos/')),
                ('status', models.CharField(choices=[('new', 'Nouvelle'), ('in_analysis', 'En analyse'), ('accepted', 'Acceptée'), ('converted', 'Convertie en OT'), ('closed', 'Clôturée'), ('rejected', 'Rejetée')], default='new', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='assets.asset')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='companies.company')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='companies.location')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='workorders.workorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
