# Generated by Django 6.1 on 2026-08-12 14:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('companies', '0001_initial'),
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('wo_type', models.CharField(choices=[('corrective', 'Corrective'), ('preventive', 'Préventive'), ('inspection', 'Inspection')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('normal', 'Normale'), ('high', 'Haute'), ('urgent', 'Urgente'), ('critical', 'Critique')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('planned', 'Planifié'), ('assigned', 'Assigné'), ('in_progress', 'En cours'), ('on_hold', 'En attente'), ('done', 'Terminé'), ('validated', 'Validé'), ('closed', 'Clôturé')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('work_performed', models.TextField(blank=True)),
                ('identified_cause', models.TextField(blank=True)),
                ('solution_applied', models.TextField(blank=True)),
                ('technician_comment', models.TextField(blank=True)),
                ('result', models.CharField(blank=True, choices=[('repaired', 'Réparé'), ('partially_repaired', 'Partiellement réparé'), ('not_repaired', 'Non réparé'), ('needs_followup', 'Nécessite une nouvelle intervention')], max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('validation_note', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='assets.asset')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='companies.company')),
                ('maintenance_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_work_orders', to='maintenance.maintenanceplan')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='companies.site')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('before', 'Avant'), ('after', 'Après')], max_length=10)),
                ('image', models.ImageField(upload_to='work_orders/photos/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='companies.company')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='workorders.workorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkOrderTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('result', models.CharField(blank=True, choices=[('conforme', 'Conforme'), ('non_conforme', 'Non conforme'), ('not_applicable', 'Non applicable')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='work_orders/tasks/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='companies.company')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workorders.workorder')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='unique_wo_number_per_company'),
        ),
    ]
